config/routes.rb
Foundry::Application.routes.draw do

  resources :landings












  get "welcome/index"

  root 'users#login'

  get '/slack/auth/', to: 'slack#callback'
  get 'oauth2callback' => 'welcome#index'
  get '/flash_teams/event_library' => 'flash_teams#event_library'
  get '/flash_teams/event_search' => 'flash_teams#event_search'
  post '/flash_teams/rename' => 'flash_teams#rename'

  resources :flash_teams do
    member do
      delete :destroy
      get :get_status
      post :update_event
      post :update_status
      post :update_original_status
      post :update_json
      post :update_flash_teams_json
      get :get_json
      post :early_completion_email
      post :get_user_name
      post :get_team_info
      post :delayed_task_finished_email
      post :create
      post :branch
      post :send_edit_team_request
      get :task_portal
      get :settings
      get :duplicate
      get :clone
      post :settings
    end
  end

  get '/flash_teams/:id/:event_id/hire_form' => 'flash_teams#hire_form'
  get '/flash_teams/:id/:event_id/hire_form/starter_task' => 'flash_teams#starter_task'

  get '/flash_teams/:id/:event_id/hire_form/task_rejection' => 'flash_teams#task_rejection'
  get '/flash_teams/:id/:event_id/hire_form/task_acceptance' => 'flash_teams#task_acceptance'
  get '/landings/:id/:event_id/view' => 'landings#view'
  post '/flash_teams/:id/:event_id/listQueue' => 'flash_teams#listQueue'
get '/flash_teams/:id/:event_id/listQueueForm' => 'flash_teams#listQueueForm'

  get '/landings/:id/:event_id/remove' => 'landings#remove'
  post '/flash_teams/:id/:event_id/hire_form/send_starter_task' => 'flash_teams#send_starter_task'
  post '/flash_teams/:id/:event_id/hire_form/send_task_acceptance' => 'flash_teams#send_task_acceptance'
  post '/flash_teams/:id/:event_id/hire_form/send_task_rejection' => 'flash_teams#send_task_rejection'
  post '/flash_teams/:id/:event_id/hire_form/send_task_available' => 'flash_teams#send_task_available'

  get '/flash_teams/:id/:event_id/panels' => 'flash_teams#panels'

  get '/flash_teams/:id/:event_id/delay' => 'flash_teams#delay'
  get '/flash_teams/:id_team/:event_id/get_delay' => 'flash_teams#get_delay'

  resources :members do
    member do
      get :invite
      get :reInvite
      get :invited
      get :confirm_email
      post :register
      get :invited_by_hiring_queue
    end
  end

  post '/activity_logs/create' => 'activity_logs#create'
  post '/activity_logs/log_update' => 'activity_logs#log_update'

  get '/users/logout' => 'users#logout'
  get '/users/login' => 'users#login'

  post '/users/post_login' => 'users#post_login'
  post '/users/post_login' => 'users#post_login'

  resources :users do
    member do
      post :create
    end
  end

  resources :pull_requests

  get '/pull_requests/:id/get_as_json' => 'pull_requests#get_as_json'

  get '/workers/index' => 'workers#index'
  get '/workers/register' => 'workers#register'
  get '/workers/confirmation' => 'workers#confirmation'
  get '/workers/apply' => 'workers#apply'
  get '/workers/apply/:panel' => 'workers#apply'
  get '/workers/:id/destroy' => 'workers#destroy'
  get '/workers/filter_workers' => 'workers#filter_workers'
  get '/workers/filter_workers_emails' => 'workers#filter_workers_emails'
  get '/workers/right_sidebar_filt' => 'workers#right_sidebar_filt'
  get '/workers/filter_workers_rightsidebar' => 'workers#filter_workers_rightsidebar'


  resources :workers do
    member do
      post :create
    end
  end





end

app/models/landing.rb
class Landing < ActiveRecord::Base
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def view
    if params[:starter_task] == "true"
      @starter_task = true
    else
      @starter_task = "false"
    end
    @id_team = params[:id]
    @id_task = params[:event_id].to_i
    @flash_team = FlashTeam.find(params[:id])
    # Extract data from the JSON
    flash_team_status = JSON.parse(@flash_team.status)
    @flash_team_json = flash_team_status['flash_teams_json']
    @flash_team_event = @flash_team_json['events'][@id_task]
    @flash_team_name = @flash_team_json['title']
    #tm = params[:task_member].split(',') role of recipient 
    @task_member = params[:task_member]
    @email = params[:email]
    @start_date_time = Time.now
    @end_date_time = Time.now + 600
    @queuePosition = 0
    @wait_time = ""
    wait_time = 0
    @removalURL = url_for :controller=>'landings', :action=>'remove', :id=>@id_team, :event_id=>@id_task, :task_member=>@task_member, :email=>@email
    @task_name = @flash_team_event['title']
    @project_overview = @flash_team_json['projectoverview']
    @task_description = @flash_team_event['notes']
    @inputs = @flash_team_event['inputs']
    #@input_link = params[:input_link]
    @outputs = @flash_team_event['outputs']
    #@output_description = params[:output_description]
    minutes = @flash_team_event['duration']
    hh, mm = minutes.divmod(60)
    @task_duration = hh.to_s 
    if hh==1
      @task_duration += " hour"
    else
      @task_duration += " hours"
    end
    if mm>0
      @task_duration += " and " + mm.to_s + " minutes"
    end

    @task_members = Array.new
    @flash_team_event['members'].each do |task_member|
      @task_members << getMemberById(@id_team, @id_task, task_member)
    end

    if @id_team.nil? or @id_team.to_i<=0 or @id_task.nil? or @id_task.to_i<0 or @email=="" or @email.nil? or @task_member.nil? or @task_member==""
      @queuePosition = -1
      return
    end

    @invitationLink = ""
    @uniq = ""

    @task_members.each do |task_member|
      if task_member['role'] == @task_member
        @uniq = task_member['uniq']
        @invitationLink = url_for :controller => 'members', :action => 'invited_by_hiring_queue', :id_team => @id_team, :uniq => @uniq, :email => @email
        break
      end
    end

    emails = Array.new
    emails = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :email=>@email, :status=>'s')
    emails1 = Array.new
    emails1 = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'s')
    if not (emails1.empty?) then
      if emails.empty? 
        @queuePosition = -1
        return
      end
    end

    uniq1 = params[:uniq]
    if uniq1!=@uniq 
      @queuePosition = -2
      l = Landing.where(:uniq => uniq1)
      l.destroy_all
      return
    end

    @relevantLanding1 = Array.new
    @relevantLanding1 = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'p')

    for l in @relevantLanding1
      m = Array.new
      m = Member.where(:email=>l.email, :uniq=>@uniq) 
      if not(m.empty?) then
        for t in m
          if t.email_confirmed 
            l.status = 'p'
            l.save
            return
          elsif Time.now>l.end_date_time
            l.status = 'd'
            l.save
          end
        end
      elsif Time.now>l.end_date_time
        l.status = 'd'
        l.save
      end
    end

    @relevantLanding = Array.new
    @relevantLanding = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'p').order('created_at')

    alreadyPresent = 0

    count = 0
    for l in @relevantLanding
      if l.email == @email then 
        alreadyPresent = 1 
        count = count+1
        break
      end
      count = count+1
    end

    if alreadyPresent == 0
      @queuePosition = @relevantLanding.length + 1
    else
      @queuePosition = count
    end

    if @queuePosition == 1 and @relevantLanding.length == 0
      wait_time = 0
    elsif @queuePosition == 1 
      wait_time = @relevantLanding[@queuePosition-1].end_date_time-Time.now
    else
      wait_time = @relevantLanding[@queuePosition-2].end_date_time-Time.now
    end

    hh, mm = wait_time.divmod(60)
    @wait_time = hh.to_s 
    if hh==1
      @wait_time += " minute"
    else
      @wait_time += " minutes"
    end
    if mm>0
      @wait_time += " and " + mm.to_i.to_s + " seconds"
    end

    if @queuePosition == 1 and @relevantLanding.length == 0 then
      @wait_time = '10 minutes'
    end

    if alreadyPresent == 0 
      @newLanding = Landing.new
      @newLanding.id_team = @id_team
      @newLanding.id_event = @id_task
      @newLanding.task_member = @task_member
      @newLanding.email = @email
      @newLanding.start_date_time = @start_date_time
      @newLanding.end_date_time = @end_date_time + wait_time
      @newLanding.queuePosition = @queuePosition
      @newLanding.status = 'p'
      deletedLanding = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'d').order('created_at')
      if @queuePosition == 1 and deletedLanding.length>0
        UserMailer.send_first_in_queue(@email, @task_member, @task_name, @flash_team_name, @wait_time, @removalURL, @task_duration, @project_overview, @task_description, @inputs, @input_link, @outputs, @output_description, @invitationLink).deliver
        @newLanding.emailSent = true
        @newLanding.emailSentTime = Time.now
      end
      @newLanding.uniq = @uniq
      @newLanding.save 
    else
      @relevantLanding = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'p').order('created_at')
      deletedLanding = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'d').order('created_at')
      if @queuePosition == 1 and not(@relevantLanding[0].emailSent) and deletedLanding.length>0
        UserMailer.send_first_in_queue(@email, @task_member, @task_name, @flash_team_name, @wait_time, @removalURL, @task_duration, @project_overview, @task_description, @inputs, @input_link, @outputs, @output_description, @invitationLink).deliver
        @relevantLanding[0].emailSent = true
        @relevantLanding[0].emailSentTime = Time.now
        @relevantLanding[0].save
      end
      return
    end
  @relevantLanding = Landing.where(:id_team=>@id_team, :id_event=>@id_task, :task_member=>@task_member, :status=>'p').order('created_at')
  end

  def remove
    timeDifference = 0
    @id_team = params[:id]
    @id_task = params[:event_id].to_i
    @task_member = params[:task_member]
    @email = params[:email]
    r = Landing.where(:id_team => @id_team, :id_event => @id_task, :task_member => @task_member, :status => 'p').order('created_at')
    index = 0
    for l in r
      if l.email == @email
        deletedTime = l.end_date_time
        l.status = 'd'
        l.save
        break
      end
      index = index+1
    end

    s = Landing.where(:id_team => @id_team, :id_event => @id_task, :task_member => @task_member, :status => 'p').order('created_at')
    if s.length>index
      if index == 0
        for i in index..s.length-1
          s[i].end_date_time = Time.now + 600*(i+1)
          s[i].save
        end

      else
        timings = Array.new
        timings<<deletedTime
        for i in index..s.length-1
          timings<<s[i].end_date_time
        end

        count = 0
        for i in index..s.length-1
          s[i].end_date_time = timings[count]
          s[i].save
          count = count+1
        end
      end
    end
  end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_error.html.erb
<p>Malformed URL. <a href="mailto:stanfordhci.odesk@gmail.com">Report bug here</a>.</p>

app/views/landings/_error1.html.erb
<p>The task is currently unavailable. Please check back later. if you believe this is an error, <a href="mailto:stanfordhci.odesk@gmail.com">email us</a>.</p>

app/views/landings/_starter_task_acceptance_email_content_landing.html.erb
<div class="row-fluid">

	<h3><i class="fa fa-angle-right"></i> Starter Task Information</h3>
          	
  	<div class="row-fluid">
  		<div class="form-panel span12">
  			<p>
  				<b>We are excited to hear you are interested in joining the <%=@task_member%> panel! </b>
  			</p>
  			<p>
  				<em>Please read the following information carefully as it contains important information for completing the starter task. </em>
  			</p>

  		</div>

  	</div>

  	<div class="row-fluid">
  		<div class="form-panel form-panel-instructions span12">

  			<p>
				In order to join the panel, we request that you complete a starter task to make sure that you have the skills and experiences needed to complete the types of tasks that will be made available. Once you complete the starter task, we will review your deliverable and make a decision. If you are invited to join the panel, you will receive a link to access the panel on boarding and confirm your membership. At that point, you will start receiving jobs as they become available.
			</p>
			<p>
				The starter task is designed to also give you exposure and experience with Foundry, our workflow management and collaboration platform. The information about the project, your starter task and compensation for your time is below. Once you accept the task, you will be taken to Foundry, which will provide you with more information.	
			</p>
  		</div>
  	</div>
  	<div class="row-fluid">

  		<div id="email-form-div" class="form-panel span12">
  			<!-- <div class="form-panel"> -->
  			<div>
		  	  	<!-- <div class="row-fluid">
		  	  		<div class="span7">
		  	  			<p style="font-size:18px;"><i class="fa fa-angle-right"></i> Task Available!</p>
					</div>
				</div> --> <!-- end div class row -->
				
				<div class="row-fluid span11">

					<p> 
						As stated in the job description, you will have <b><em><%=@task_duration%></em></b> to complete this task. Please make sure to track your working hours on Upwork and to start your task on Foundry. Additional information regarding compensation can be found in the email describing the starter task. For your reference, we have included the job description below:
					</p>
						
						<p><b>Project overview:</b> <%= raw @project_overview%></p>
						<p><b>Task description:</b> <%= raw @task_description%></p>
						
						<p>
							<%if !@inputs.empty?%>
								<b>Input(s):</b> For this task, you will receive the following input(s): <%=@inputs%>.
							<% end %> 
							
							<%if !@input_link.nil?%>
								You can access the input(s) at the following link: <a href="<%=@input_link%>"><%=@input_link%></a>
							<%end%>
						</p>
						
						<%if !@outputs.empty?%>
							<p><b>Deliverable(s):</b> <%=@outputs%></p>
						<% end %>
						
						<%if !@output_description.nil?%>
							<p><b>Deliverable information:</b> <%=@output_description%></p>
						<%end%>
						
						<p>
							<b>How to start:</b> We are asking you to use our platform, Foundry, to keep track of your progress and submit your work. Click the link below to sign up for this project on Foundry. 
						</p>
						
						<p><%=link_to "Click here to register for this position on Foundry", @invitationLink%></p>

						<p>
							After you sign up, you will receive a unique link to the project, which you should use to access your task, keep track of your progress and submit your work. If you are unfamiliar with Foundry, view the Foundry tour by clicking the "Start Foundry Tour" button on the top left of the page.  Feel free to contact us (<%=ENV['DEFAULT_EMAIL']%>) if you have any remaining questions.
						</p>  
						
						<p>
							If you would not like to join the panel any more, <%=link_to "Click here", @removalURL, :data=>{:confirm=>"Are you sure you want to be removed from the hiring queue?"}%> to decline the starter task.
						</p>

			
						<p>
							Thank you for involvement in this project and we look forward to receiving your work!
						</p>

						<p>
							Best, <br />
							Stanford HCI Research Team
						</p>
					
				</div>
	
          	  
			</div><!-- /form-panel -->
		</div><!-- /span7 -->
  		  			
  	</div><!-- /row -->
</div>

app/views/landings/_task_hiring_email1.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta http-equiv="refresh" content="60">
    <title>Foundry Hiring Portal</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag    "application"%>
    <%= stylesheet_link_tag    "hiring-panel"%>
    <%= stylesheet_link_tag    "font-awesome"%>


  </head>


  <body>

  <section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
	  <header class="header black-bg">
              <!--
			  <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
				-->
              
            <!--logo start-->
            <!-- <p class="logo"><b>FOUNDRY HIRING PORTAL</b></p> -->
            <a href="#" class="logo"><b>FOUNDRY HIRING PORTAL</b></a>
            
            <!--logo end-->
             <div class="top-menu">
            	<ul class="nav pull-right top-menu">
	            	<li><%=link_to "Back to Foundry", edit_flash_team_path, :class=> "logout"%></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <!-- div class="span3" id="sidebar"> -->
              <!-- sidebar menu start-->
              <!-- <ul class="sidebar-nav"> -->
              
              <!-- <div class="span3" id="sidebar"> -->
              <!-- sidebar menu start-->
             <!--  <ul class="sidebar-menu"> -->
	              
	        <div id="sidebar"  class="span3 nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">

              	  <h5 class="project-name">Project: <%=@flash_team_json["title"]%></h5>
              	   <h6 class="task-name">Task: <%=@flash_team_event["title"]%></h6>
              	  	     
                   <li class=<%=@panels_active%>>
                   
                   <%= link_to raw('<i class="fa fa-th"></i><span>Edit Panels</span>'), controller: "flash_teams", action: "panels" %> 			
                          
                  </li>
                  

                  <li class="sub-menu">
                      <a href="javascript:;" >
	                      <i class="fa fa-envelope-o"></i>
                          <!-- <i class="fa fa-desktop"></i> -->
                          <span>Hiring Emails</span>
                      </a>
                      <ul class="sub">
                          <li class=<%=@task_avail_active%>><%=link_to "Task Available", controller: "flash_teams", action: "hire_form"%> </li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <!-- <i class="fa fa-cogs"></i> -->
                          <i class="fa fa-tasks"></i>
                          <span>View Other Tasks</span>
                      </a>
                      <ul class="sub">
                          <%i = 0%>
                          <%@flash_team_json['events'].each do |event|%>
                          
                          	<% if i == @id_task %>
								<li class="active">
							<% else %>
								<li>
							<% end %>
								<%=link_to event["title"], :controller => "flash_teams", :action => "hire_form", :event_id => i %></li>
								<%i+= 1%>
						<% end %>
                      </ul>
                  </li>
                  
                  <!-- <li><%#link_to "Back to Foundry", edit_flash_team_path, :class=> "logout"%></li> -->

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
          	          	
          		<%= yield %>
          	
		</section><! --/wrapper -->
      </section><!-- /MAIN CONTENT -->

      <!--main content end-->
      <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2014 - Stanford HCI Group
              <a href="#" class="go-top">
                  <i class="fa fa-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->
  </section>

    <!-- js placed at the end of the document so the pages load faster -->
	<%= javascript_include_tag "/assets/jquery" %>
	<%= javascript_include_tag "/assets/jquery_ujs" %>
	<%= javascript_include_tag "bootstrap/bootstrap.min" %>
	<%= javascript_include_tag "/assets/jquery.dcjqaccordion.2.7" %>


  </body>
</html>

app/views/landings/_task_hiring_email2.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta http-equiv="refresh" content="60">

    <title>Foundry Hiring Portal</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag    "application"%>
    <%= stylesheet_link_tag    "hiring-panel"%>
    <%= stylesheet_link_tag    "font-awesome"%>


  </head>

  <body>

  <section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
	  <header class="header black-bg">
              <!--
			  <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
				-->
              
            <!--logo start-->
            <!-- <p class="logo"><b>FOUNDRY HIRING PORTAL</b></p> -->
            <a href="#" class="logo"><b>FOUNDRY HIRING PORTAL</b></a>
            
            <!--logo end-->
             <div class="top-menu">
            	<ul class="nav pull-right top-menu">
	            	<li><%=link_to "Back to Foundry", edit_flash_team_path, :class=> "logout"%></li>
            	</ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
          <!-- div class="span3" id="sidebar"> -->
              <!-- sidebar menu start-->
              <!-- <ul class="sidebar-nav"> -->
              
              <!-- <div class="span3" id="sidebar"> -->
              <!-- sidebar menu start-->
             <!--  <ul class="sidebar-menu"> -->
	              
	        <div id="sidebar"  class="span3 nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">

              	  <h5 class="project-name">Project: <%=@flash_team_json["title"]%></h5>
              	   <h6 class="task-name">Task: <%=@flash_team_event["title"]%></h6>
              	  	     
                   <li class=<%=@panels_active%>>
                   
                   <%= link_to raw('<i class="fa fa-th"></i><span>Edit Panels</span>'), controller: "flash_teams", action: "panels" %> 			
                          
                  </li>
                  

                  <li class="sub-menu">
                      <a href="javascript:;" >
	                      <i class="fa fa-envelope-o"></i>
                          <!-- <i class="fa fa-desktop"></i> -->
                          <span>Hiring Emails</span>
                      </a>
                      <ul class="sub">
                          <li class=<%=@task_avail_active%>><%=link_to "Task Available", controller: "flash_teams", action: "hire_form"%> </li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <!-- <i class="fa fa-cogs"></i> -->
                          <i class="fa fa-tasks"></i>
                          <span>View Other Tasks</span>
                      </a>
                      <ul class="sub">
                          <%i = 0%>
                          <%@flash_team_json['events'].each do |event|%>
                          
                          	<% if i == @id_task %>
								<li class="active">
							<% else %>
								<li>
							<% end %>
								<%=link_to event["title"], :controller => "flash_teams", :action => "hire_form", :event_id => i %></li>
								<%i+= 1%>
						<% end %>
                      </ul>
                  </li>
                  
                  <!-- <li><%#link_to "Back to Foundry", edit_flash_team_path, :class=> "logout"%></li> -->

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
          	          	
          		<%= yield %>
          	
		</section><! --/wrapper -->
      </section><!-- /MAIN CONTENT -->

      <!--main content end-->
      <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2014 - Stanford HCI Group
              <a href="#" class="go-top">
                  <i class="fa fa-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->
  </section>

    <!-- js placed at the end of the document so the pages load faster -->
	<%= javascript_include_tag "/assets/jquery" %>
	<%= javascript_include_tag "/assets/jquery_ujs" %>
	<%= javascript_include_tag "bootstrap/bootstrap.min" %>
	<%= javascript_include_tag "/assets/jquery.dcjqaccordion.2.7" %>
	


  </body>
</html>

app/views/landings/_task_rejection_email_content_landing.html.erb
<div class="row-fluid">
	
	<h3><i class="fa fa-angle-right"></i> Task Unavailable!</h3>
          	
  	<!-- INPUT MESSAGES -->
  	<div class="row-fluid">
  		<div id="email-form-div" class="form-panel span12">
  			<!-- <div class="form-panel"> -->
  			<div>
		  	  	<!-- <div class="row-fluid">
		  	  		<div class="span7">
		  	  			<p style="font-size:18px;"><i class="fa fa-angle-right"></i> Task Unavailable!</p>
					</div>
				</div>  --><!-- end div class row -->
				
				<div class="row-fluid span12">
					<p>Thank you for applying for the <em><%=@task_member%></em> role to work on the <em><%=@task_name%></em> task as part of the <b><em><%=@flash_team_name%></em></b> project. Unfortunately, the job is no longer available. As you know, we use an on-demand hiring process that assigns the job to the first person who claims it. However, we have more upcoming projects and we will keep you posted as other job opportunities become available.</p>


					<p>If you don't want to be informed about our future job opportunities, please <a href="mailto:stanfordhci.odesk@gmail.com"> email us </a> with your name in the content.</p>

					<p>
						Best, <br />
						Stanford HCI Research Team
					</p>
					
				</div>
	
          	  
			</div><!-- /form-panel -->
		</div><!-- /span7 -->
  		  			
  	</div><!-- /row -->
</div>

app/views/landings/_task_removal_email_content_landing.html.erb
<div class="row-fluid">
	
	<h3><i class="fa fa-angle-right"></i> Hiring Emails</h3>
          	
  	<!-- INPUT MESSAGES -->
  	<div class="row-fluid">
  		<div id="email-form-div" class="form-panel span12">
  			<!-- <div class="form-panel"> -->
  			<div>
		  	  	<div class="row-fluid">
		  	  		<div class="span7">
		  	  			<p style="font-size:18px;"><i class="fa fa-angle-right"></i>Removed from the hiring queue!</p>
					</div>
				</div> <!-- end div class row -->
				
				<div class="row-fluid span11">
					<p>
						You have been successfully removed from the hiring queue. We are sorry you could not work with us this time. We hope to have you on board sometime later.</p>
<p>We would love your feedback. Please submit your feedback either through the chat or via <a href="mailto:stanfordhci.odesk@gmail.com">email</a>.</p>
						<p>
							Best, <br />
							Stanford HCI Research Team
						</p>
					
				</div>
	
          	  
			</div><!-- /form-panel -->
		</div><!-- /span7 -->
  		  			
  	</div><!-- /row -->
</div>

app/views/landings/remove.html.erb
<%= render partial: "task_removal_email_content_landing" %>

app/views/landings/view.html.erb
<% if @queuePosition==-1 %>
<%= render partial: "error" %>
<% elsif @queuePosition==-2 %>
<%= render partial: "error1" %>
<% elsif @queuePosition == 1 || @starter_task == true%>
	<% if @starter_task == true %>
		<%= render partial: "starter_task_acceptance_email_content_landing", layout: "task_hiring_email" %>
	<% else %>
		<%= render partial: "task_acceptance_email_content_landing", layout: "task_hiring_email" %>
	<% end %>
<% elsif @queuePosition == 0 %>
<%= render partial: "task_rejection_email_content_landing", layout: "task_hiring_email" %>
<% else %>
<%= render partial: "task_waiting_email_content_landing", layout: "task_hiring_email" %>
<% end %>